#!/usr/bin/env bash
# pass1.sh — Pass 1 of the "prove it on merkle" simulation (docs/plans/05 §2, WO-18).
#
# Purpose: prove the *stack* is healthy so that every later (Pass 2 / Pass 3)
# failure can be blamed on Burrow's *tooling*, not on merkle. Runs headless, no
# IDE. Each step prints exactly one `PASS <step>` or `FAIL <step>` line; the
# script exits 0 only if every step passed.
#
# It drives merkle's own lifecycle script (infra/merkle) and test fixtures
# (infra/test/{smoke.sh,mock/*}) — it invents no new infra.
#
# Usage:
#   bash docs/plans/scripts/pass1.sh            # start stack, run all steps, tear down
#   KEEP_UP=1 bash .../pass1.sh                 # leave api+web running at the end
#   MERKLE_DIR=~/src/merkle bash .../pass1.sh   # point at a different checkout
#
# Env overrides (all optional):
#   MERKLE_DIR      default $HOME/Projects/merkle
#   API_BASE        default http://127.0.0.1:8080
#   WEB_BASE        default http://127.0.0.1:5173
#   DATABASE_URL    default postgres://nodewatch:nodewatch@localhost:5432/nodewatch?sslmode=disable
#   HEALTH_TIMEOUT  seconds to wait for /healthz after --start (default 90)
#   KEEP_UP         1 = do not run `merkle --down` at the end (default 0)
#
# NOT `set -e`: we assess each step ourselves and keep going so the summary is
# complete even when an early step fails.
set -uo pipefail

# ── config ────────────────────────────────────────────────────────────────────
MERKLE_DIR="${MERKLE_DIR:-$HOME/Projects/merkle}"
INFRA="$MERKLE_DIR/infra"
MERKLE="$INFRA/merkle"
API="${API_BASE:-http://127.0.0.1:8080}"
WEB="${WEB_BASE:-http://127.0.0.1:5173}"
DB_URL="${DATABASE_URL:-postgres://nodewatch:nodewatch@localhost:5432/nodewatch?sslmode=disable}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-90}"
KEEP_UP="${KEEP_UP:-0}"
ORG="00000000-0000-0000-0000-000000000001"           # seeded default org
API_KEY_ETH="test-key-eth"                            # seeded eth-validator-01 key

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENDPOINTS_MD="$SCRIPT_DIR/pass1-endpoints.md"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/pass1.XXXXXX")"

# ── reporting ─────────────────────────────────────────────────────────────────
n_pass=0; n_fail=0; declare -a FAILED=()
hdr()  { printf '\n\033[1m── %s\033[0m\n' "$*"; }
pass() { printf '\033[32mPASS\033[0m %s\n' "$*"; n_pass=$((n_pass+1)); }
fail() { printf '\033[31mFAIL\033[0m %s\n' "$*"; n_fail=$((n_fail+1)); FAILED+=("$*"); }
die()  { printf '\033[1;31mFATAL\033[0m %s\n' "$*" >&2; exit 2; }
note() { printf '  · %s\n' "$*"; }

# ── helpers ───────────────────────────────────────────────────────────────────
have() { command -v "$1" >/dev/null 2>&1; }
http_code() { curl -sS -o /dev/null -w '%{http_code}' "$@" 2>/dev/null || echo 000; }
psql1() { psql "$DB_URL" -tAc "$1" 2>/dev/null | tr -d '[:space:]'; }

wait_2xx() { # url timeout_s
  local url="$1" t="$2" n=0
  until [[ "$(http_code "$url")" =~ ^2 ]]; do
    sleep 1; n=$((n+1)); (( n < t )) || return 1
  done
}

# Parse e2e.sh's (ANSI-coloured) output into a per-route markdown table.
write_endpoints_md() { # e2e_log_path sweep_rc
  local log="$1" rc="$2"
  E2E_LOG="$log" SWEEP_RC="$rc" API_BASE_V="$API" python3 - "$ENDPOINTS_MD" <<'PY'
import os, re, sys
out = sys.argv[1]
log, rc, api = os.environ["E2E_LOG"], os.environ["SWEEP_RC"], os.environ["API_BASE_V"]
ansi = re.compile(r"\x1b\[[0-9;]*m")
rows, section = [], ""
sec = re.compile(r"^\d+\.\s+\S")
ok  = re.compile(r"^ok\s+(\S+)\s+(\S+)\s+(\d+)")
bad = re.compile(r"^FAIL\s+(\S+)\s+(\S+)\s+got\s+(\S+)\s+want\s+(\S+)")
for raw in open(log, errors="replace"):
    line = ansi.sub("", raw).rstrip("\n")
    s = line.strip()
    if sec.match(s):
        section = s
    elif s.startswith("ok "):
        m = ok.match(s)
        if m: rows.append((section, m.group(1), m.group(2), "PASS", m.group(3), ""))
    elif s.startswith("FAIL "):
        m = bad.match(s)
        if m: rows.append((section, m.group(1), m.group(2), "FAIL", m.group(3), f"want {m.group(4)}"))
npass = sum(1 for r in rows if r[3] == "PASS")
nfail = sum(1 for r in rows if r[3] == "FAIL")
with open(out, "w") as f:
    f.write("# Pass 1 — endpoint sweep\n\n")
    f.write(f"Generated by `docs/plans/scripts/pass1.sh` step 4 (runner: `infra/test/mock/e2e.sh` against `{api}`).\n\n")
    f.write(f"**Result:** {npass} passed · {nfail} failed · sweep exit `{rc}` · {len(rows)} routes.\n\n")
    f.write("| Group | Method | Route | Result | Status | Expected |\n")
    f.write("|---|---|---|---|---|---|\n")
    for g, meth, path, res, code, exp in rows:
        f.write(f"| {g} | `{meth}` | `{path}` | {res} | {code} | {exp} |\n")
    f.write("\n> Expected statuses (incl. deliberate 401/403 on user-scoped & superadmin routes with "
            "Auth0 OFF) are asserted inside `e2e.sh`; a blank Expected column means the route matched.\n")
print(f"wrote {out} ({len(rows)} routes)")
PY
}

# ── preflight ─────────────────────────────────────────────────────────────────
for t in curl docker psql python3; do have "$t" || die "missing required tool: $t"; done
[[ -x "$MERKLE" ]] || die "merkle launcher not found/executable at $MERKLE"
docker info >/dev/null 2>&1 || die "Docker isn't running (needed for the nodewatch-db container)."

started_here=0
STACK_UP=0

cleanup() {
  if [[ "$started_here" == "1" && "$KEEP_UP" != "1" ]]; then
    hdr "teardown"; ( cd "$INFRA" && "$MERKLE" --down ) || true
  elif [[ "$KEEP_UP" == "1" ]]; then
    note "KEEP_UP=1 — leaving api+web running (./merkle --down to stop)."
  fi
  rm -rf "$TMP"
}
trap cleanup EXIT

echo "Pass 1 — merkle stack truth"
echo "  merkle : $MERKLE"
echo "  api    : $API      web: $WEB"
echo "  db     : $DB_URL"

# ── step 1 — start + health ──────────────────────────────────────────────────
hdr "1. ./merkle --start → /healthz + web root 200 within ${HEALTH_TIMEOUT}s"
if [[ "$(http_code "$API/healthz")" == "200" ]]; then
  note "stack already up — reusing it (won't tear down unless KEEP_UP left unset AND we started it)."
else
  started_here=1
  ( cd "$INFRA" && "$MERKLE" --start ) >"$TMP/start.log" 2>&1 || note "merkle --start returned non-zero; probing anyway (see $TMP/start.log)"
fi
if wait_2xx "$API/healthz" "$HEALTH_TIMEOUT"; then
  web_code="$(http_code "$WEB/")"
  if [[ "$web_code" =~ ^[23] ]]; then
    STACK_UP=1; pass "step1-start-health (healthz=200 web=$web_code)"
  else
    fail "step1-start-health (web root=$web_code, expected 2xx/3xx)"
  fi
else
  fail "step1-start-health (healthz never reached 200; see $TMP/start.log)"
fi

run_rest() { [[ "$STACK_UP" == "1" ]]; }

# ── step 2 — seed + backfill idempotence ─────────────────────────────────────
# NOTE (grounding, corrects 05 §2): backfill.sql keys rows on the PK
# (org_id,node_id,ts,metric_name) where ts = generate_series(now()-24h, now(),
# 5min). Because the grid is anchored to now(), a second run's timestamps differ
# and INSERT fresh rows — the raw node_metrics count *grows*, it does not stay
# constant. The real guarantee (and what "idempotent" means here) is: a re-run
# does not ERROR (ON CONFLICT … DO UPDATE) and leaves valid history. seed.sh
# likewise APPENDS live ticks, so neither is count-invariant. We therefore assert
# "applies twice cleanly + history present", not "row counts unchanged".
hdr "2. seed + backfill apply idempotently (clean re-run, history present)"
if run_rest; then
  apply_backfill() { psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$INFRA/test/mock/backfill.sql" >>"$TMP/backfill.log" 2>&1; }
  # a light live-ingest fixture exercise (non-asserting; the real /ingest check is step 5)
  bash "$INFRA/test/mock/seed.sh" "$API" 3 >>"$TMP/seed.log" 2>&1 || note "seed.sh returned non-zero (rate-limit/timing) — non-fatal"
  apply_backfill; rc1=$?
  apply_backfill; rc2=$?
  pts="$(psql1 "SELECT count(*) FROM node_metrics WHERE org_id='$ORG' AND metric_name='cpu_percent'")"
  if [[ "$rc1" == "0" && "$rc2" == "0" && -n "$pts" && "$pts" -gt 0 ]]; then
    pass "step2-backfill-idempotent (re-ran clean; cpu_percent points=$pts)"
  else
    fail "step2-backfill-idempotent (rc1=$rc1 rc2=$rc2 cpu_points=${pts:-<none>})"
  fi
else
  fail "step2-backfill-idempotent (skipped — stack not up)"
fi

# ── step 3 — smoke ────────────────────────────────────────────────────────────
hdr "3. infra/test/smoke.sh (happy-path curl smoke)"
if run_rest; then
  if bash "$INFRA/test/smoke.sh" "$API" >"$TMP/smoke.log" 2>&1; then
    pass "step3-smoke ($(grep -Eo '[0-9]+ passed' "$TMP/smoke.log" | tail -1))"
  else
    fail "step3-smoke ($(grep -Eo '[0-9]+ passed, [0-9]+ failed' "$TMP/smoke.log" | tail -1); see $TMP/smoke.log)"
  fi
else
  fail "step3-smoke (skipped — stack not up)"
fi

# ── step 4 — endpoint sweep ───────────────────────────────────────────────────
# newman/the Postman collection is the documented tool, but newman isn't
# installed here and infra/test/mock/e2e.sh IS the endpoint sweep (it hits every
# route group, chains created IDs, asserts the documented status per route incl.
# the deliberate 401/403s, exit 0 only if all match). It's the right runner (05 §2
# step 4 explicitly says "or e2e.sh if that's its job — read it first"; it is).
hdr "4. endpoint sweep — infra/test/mock/e2e.sh → pass1-endpoints.md"
if run_rest; then
  if bash "$INFRA/test/mock/e2e.sh" "$API" >"$TMP/e2e.log" 2>&1; then sweep_rc=0; else sweep_rc=$?; fi
  write_endpoints_md "$TMP/e2e.log" "$sweep_rc"
  # totals come from the generated report (e2e.sh's own summary line is ANSI-interleaved)
  totals="$(grep -Eo '[0-9]+ passed' "$ENDPOINTS_MD" | head -1), $(grep -Eo '[0-9]+ failed' "$ENDPOINTS_MD" | head -1)"
  if [[ "$sweep_rc" == "0" ]]; then
    pass "step4-endpoint-sweep ($totals → $ENDPOINTS_MD)"
  else
    fail "step4-endpoint-sweep ($totals; see $ENDPOINTS_MD and $TMP/e2e.log)"
  fi
else
  fail "step4-endpoint-sweep (skipped — stack not up)"
fi

# ── step 5 — ingest door ──────────────────────────────────────────────────────
hdr "5. ingest door — POST /ingest (X-API-Key) then read it back via /api/metrics"
if run_rest; then
  eth_id="$(curl -sS "$API/api/nodes" -H "X-Org-Id: $ORG" \
    | python3 -c "import sys,json;print(next((n['id'] for n in json.load(sys.stdin) if n['name']=='eth-validator-01'),''))" 2>/dev/null)"
  ing_code="$(http_code -X POST "$API/ingest" -H 'Content-Type: application/json' \
    -H "X-API-Key: $API_KEY_ETH" -d @"$INFRA/test/mock/bodies/ingest-eth-tick.json")"
  from="$(python3 -c "import datetime;print((datetime.datetime.now(datetime.UTC)-datetime.timedelta(hours=1)).strftime('%Y-%m-%dT%H:%M:%SZ'))")"
  to="$(python3   -c "import datetime;print((datetime.datetime.now(datetime.UTC)+datetime.timedelta(minutes=5)).strftime('%Y-%m-%dT%H:%M:%SZ'))")"
  metrics_json="$TMP/metrics.json"
  m_code="$(curl -sS -o "$metrics_json" -w '%{http_code}' \
    "$API/api/metrics?node_id=$eth_id&metric_name=cpu_percent&from=$from&to=$to" -H "X-Org-Id: $ORG")"
  points="$(python3 -c "import sys,json
try:
    d=json.load(open('$metrics_json'))
    if isinstance(d,dict):
        d=d.get('points') or d.get('data') or d.get('series') or next((v for v in d.values() if isinstance(v,list)),[])
    print(len(d) if isinstance(d,list) else 0)
except Exception:
    print(0)" 2>/dev/null)"
  if [[ "$ing_code" =~ ^2 && "$m_code" =~ ^2 && "${points:-0}" -gt 0 ]]; then
    pass "step5-ingest (POST=$ing_code, /api/metrics=$m_code, points=$points)"
  else
    fail "step5-ingest (POST=$ing_code metrics=$m_code points=${points:-0} node=${eth_id:-<none>})"
  fi
else
  fail "step5-ingest (skipped — stack not up)"
fi

# ── step 6 — restart-api mid-traffic ─────────────────────────────────────────
hdr "6. ./merkle --restart-api recovers < 5s with no orphaned listeners"
if run_rest; then
  ( while true; do curl -sf -o /dev/null "$API/api/nodes" -H "X-Org-Id: $ORG" || true; sleep 0.2; done ) &
  traffic_pid=$!
  ( cd "$INFRA" && "$MERKLE" --restart-api ) >"$TMP/restart.log" 2>&1 || note "restart-api returned non-zero (see $TMP/restart.log)"
  # time how long until /healthz is back to 200
  t0=$SECONDS; recovered=-1
  while (( SECONDS - t0 < 20 )); do
    [[ "$(http_code "$API/healthz")" == "200" ]] && { recovered=$((SECONDS - t0)); break; }
    sleep 1
  done
  kill "$traffic_pid" 2>/dev/null; wait "$traffic_pid" 2>/dev/null || true
  # orphan check: exactly one listener on :8080
  listeners="$(lsof -nP -iTCP:8080 -sTCP:LISTEN -t 2>/dev/null | sort -u | wc -l | tr -d ' ')"
  if [[ "$recovered" -ge 0 && "$recovered" -le 5 && "$(http_code "$API/healthz")" == "200" && "${listeners:-0}" -le 1 ]]; then
    pass "step6-restart-api (recovered in ${recovered}s, listeners=$listeners)"
  else
    fail "step6-restart-api (recovered=${recovered}s healthz=$(http_code "$API/healthz") listeners=${listeners})"
  fi
else
  fail "step6-restart-api (skipped — stack not up)"
fi

# ── step 7 — down/up idempotence, world survives ─────────────────────────────
hdr "7. ./merkle --down && --start — world intact (db volume survives)"
if run_rest; then
  nodes_before="$(psql1 "SELECT count(*) FROM nodes WHERE deleted_at IS NULL")"
  ( cd "$INFRA" && "$MERKLE" --down ) >"$TMP/down.log" 2>&1 || note "down returned non-zero"
  started_here=1
  ( cd "$INFRA" && "$MERKLE" --start ) >"$TMP/restart-full.log" 2>&1 || note "restart --start returned non-zero"
  if wait_2xx "$API/healthz" "$HEALTH_TIMEOUT"; then
    nodes_after="$(psql1 "SELECT count(*) FROM nodes WHERE deleted_at IS NULL")"
    if [[ -n "$nodes_before" && "$nodes_before" == "$nodes_after" && "$nodes_before" -gt 0 ]]; then
      pass "step7-down-up (nodes=$nodes_after survived restart)"
    else
      fail "step7-down-up (nodes before=$nodes_before after=$nodes_after)"
    fi
  else
    fail "step7-down-up (stack did not come back up after down/start)"
  fi
else
  fail "step7-down-up (skipped — stack not up)"
fi

# ── summary ───────────────────────────────────────────────────────────────────
hdr "summary"
printf 'PASS=%d  FAIL=%d\n' "$n_pass" "$n_fail"
if (( n_fail > 0 )); then
  printf 'failed steps:\n'; printf '  - %s\n' "${FAILED[@]}"
fi
exit $(( n_fail > 0 ? 1 : 0 ))
