/*---------------------------------------------------------------------------------------------
 *  Burrow — Go IDE. Licensed under the MIT License.
 *  Fork of Code - OSS (Copyright (c) Microsoft Corporation). See THIRD_PARTY_NOTICES.md.
 *--------------------------------------------------------------------------------------------*/

// The ordering rules, which are the whole feature: a plan that lets you write a
// handler before the store it calls is worse than no plan. planModel.ts imports
// nothing from 'vscode', so out/planModel.js is a plain CommonJS module.
// Run: `npm test` (after a compile) or `node test/planModel.test.js`.

'use strict';

const assert = require('node:assert');
const {
	buildPlan, dependents, goDeclares, goImports, isIgnored, kindOf,
	leadingComment, orderViolations, pairTests, routeIndex, topoSort, tsDeclares, tsImports,
} = require('../out/planModel');

const file = (path, text = '') => ({ path, text, bytes: Buffer.byteLength(text) });

/** A tiny two-package Go module plus a web app, enough to exercise every rule. */
const project = () => [
	file('backend/go.mod', 'module example.com/app\n\ngo 1.25.0\n'),
	file('backend/go.sum', 'github.com/x/y v1.0.0 h1:abc=\n'),
	file('backend/models/node.go', '// Package models holds the shapes every store reads and writes.\npackage models\n\ntype Node struct {\n\tID string\n}\n'),
	file('backend/store/store.go', 'package store\n\nimport (\n\t"context"\n\n\t"example.com/app/models"\n)\n\nfunc List(ctx context.Context) ([]models.Node, error) {\n\treturn nil, nil\n}\n'),
	file('backend/store/store_test.go', 'package store\n\nimport "testing"\n\nfunc TestList(t *testing.T) {}\n'),
	file('backend/router.go', 'package main\n\nimport (\n\t"github.com/go-chi/chi/v5"\n\n\t"example.com/app/store"\n)\n\nfunc Routes() *chi.Mux {\n\tr := chi.NewRouter()\n\tr.Route("/api", nil)\n\t_ = store.List\n\treturn r\n}\n'),
	file('backend/migrations/001_init.sql', '-- the nodes table\nCREATE TABLE nodes (id text primary key);\n'),
	file('web/package.json', '{"name":"web"}'),
	file('web/src/lib/format.ts', 'export function format(n: number): string {\n\treturn String(n);\n}\n'),
	file('web/src/ui/Badge.tsx', "import { format } from '../lib/format';\nexport function Badge() { return format(1); }\n"),
	file('README.md', '# app\n'),
	file('node_modules/left-pad/index.js', 'module.exports = 1;'),
];

/** A flows.json with `traced` dialled to whatever the case needs. */
const flows = (traced) => ({
	backend: '/ref/backend',
	coverage: { traced },
	flows: [
		{ method: 'GET', path: '/api/nodes', file: 'router.go', nodes: [{ file: 'store/store.go' }] },
		{ method: 'POST', path: '/api/nodes', file: 'router.go', middleware: [{ file: 'middleware/auth.go' }] },
	],
});

const stageOf = (plan, id) => plan.steps[id].stage;
const stageIndex = (plan, id) => plan.stages.findIndex((s) => s.id === stageOf(plan, id));

const cases = {
	// --- reading the source ---------------------------------------------------
	'a grouped import block yields every path': () => {
		const text = 'package x\n\nimport (\n\t"context"\n\tchimw "github.com/go-chi/chi/v5/middleware"\n\n\t"example.com/app/models"\n)\n';
		assert.deepStrictEqual(goImports(text), ['context', 'github.com/go-chi/chi/v5/middleware', 'example.com/app/models']);
	},
	'a single-line import is read too': () => {
		assert.deepStrictEqual(goImports('package x\n\nimport "fmt"\n'), ['fmt']);
	},
	'exported Go declarations include grouped types and method names': () => {
		const text = 'package x\n\ntype (\n\tNode struct{}\n\tprivate struct{}\n)\n\nfunc (h *H) Serve() {}\nfunc helper() {}\nconst Limit = 3\nvar Default = 1\n';
		assert.deepStrictEqual(goDeclares(text), ['Node', 'Serve', 'Limit', 'Default']);
	},
	'TypeScript exports and relative imports are read': () => {
		const text = "import { format } from '../lib/format';\nimport './Badge.css';\nexport function Badge() {}\nexport const size = 2;\n";
		assert.deepStrictEqual(tsImports(text), ['../lib/format', './Badge.css']);
		assert.deepStrictEqual(tsDeclares(text), ['Badge', 'size']);
	},
	'a licence banner is not mistaken for the summary': () => {
		const text = '/*----\n * Copyright\n *---*/\n\n// store.go — reading nodes back out.\npackage store\n';
		assert.strictEqual(leadingComment(text, 'go'), 'store.go — reading nodes back out.');
	},
	'generated-code markers are not summaries': () => {
		assert.strictEqual(leadingComment('// Code generated by protoc. DO NOT EDIT.\npackage x\n', 'go'), '');
	},

	// --- what counts as source ------------------------------------------------
	'build output and dependencies are not steps': () => {
		assert.strictEqual(isIgnored('node_modules/x/index.js'), true);
		assert.strictEqual(isIgnored('frontend/dist/app.js'), true);
		assert.strictEqual(isIgnored('backend/__debug_bin123'), true);
		assert.strictEqual(isIgnored('backend/app.go'), false);
	},
	'a real .env is skipped but .env.example is the config contract': () => {
		assert.strictEqual(isIgnored('infra/.env'), true);
		assert.strictEqual(isIgnored('infra/.env.example'), false);
	},
	'kinds separate tests, manifests and lockfiles': () => {
		assert.deepStrictEqual(
			['a/store.go', 'a/store_test.go', 'go.mod', 'go.sum', 'ui/Badge.tsx', 'x.sql', 'vite.config.ts'].map(kindOf),
			['go', 'gotest', 'manifest', 'lock', 'tsx', 'sql', 'manifest'],
		);
	},

	// --- ordering -------------------------------------------------------------
	'topoSort puts dependencies before the things that need them': () => {
		const edges = new Map([['app', new Set(['store'])], ['store', new Set(['models'])], ['models', new Set()]]);
		assert.deepStrictEqual(topoSort(['app', 'store', 'models'], edges), ['models', 'store', 'app']);
	},
	'topoSort keeps every node when there is a cycle': () => {
		const edges = new Map([['a', new Set(['b'])], ['b', new Set(['a'])]]);
		assert.deepStrictEqual(topoSort(['a', 'b'], edges).sort(), ['a', 'b']);
	},
	'a test follows the file it tests': () => {
		assert.deepStrictEqual(
			pairTests(['store.go', 'store_test.go', 'cache.go', 'orphan_test.go', 'cache_test.go']),
			['store.go', 'store_test.go', 'cache.go', 'cache_test.go', 'orphan_test.go'],
		);
	},

	// --- the plan -------------------------------------------------------------
	'foundations come first, and go.sum is not a step of its own': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.strictEqual(plan.stages[0].id, '@foundations');
		// `go mod tidy`, which the go.mod step runs, writes go.sum. A step for it
		// would ask for a command that has already succeeded.
		assert.deepStrictEqual(plan.stages[0].steps, ['backend/go.mod', 'web/package.json']);
		assert.strictEqual(plan.steps['backend/go.sum'], undefined);
	},
	'a toolchain-written file is a generate step carrying its command': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const gomod = plan.steps['backend/go.mod'];
		assert.strictEqual(gomod.mode, 'generate');
		assert.strictEqual(gomod.command, 'go mod init example.com/app && go mod tidy');
		assert.strictEqual(gomod.commandCwd, 'backend');
		assert.strictEqual(plan.steps['web/package.json'].mode, 'write');
	},
	'a generate step runs its command and then proves the file exists': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const checks = plan.steps['backend/go.mod'].checks;
		assert.deepStrictEqual(checks.map((c) => c.kind), ['shell', 'exists']);
		assert.strictEqual(checks[0].cmd, 'go mod init example.com/app && go mod tidy');
		assert.strictEqual(checks[0].cwd, 'backend');
	},
	'a lockfile is generated by its package manager, not typed': () => {
		const plan = buildPlan([...project(), file('web/package-lock.json', '{"lockfileVersion":3}')], { name: 'app', reference: '/ref' });
		const lock = plan.steps['web/package-lock.json'];
		assert.strictEqual(lock.mode, 'generate');
		assert.strictEqual(lock.command, 'npm install');
		assert.strictEqual(lock.commandCwd, 'web');
	},
	'prose and diagrams are copied, not written': () => {
		const plan = buildPlan([...project(), file('docs/flow.puml', '@startuml\n@enduml\n')], { name: 'app', reference: '/ref' });
		assert.strictEqual(kindOf('docs/flow.puml'), 'doc');
		assert.strictEqual(plan.steps['docs/flow.puml'].mode, 'copy');
		assert.strictEqual(plan.steps['README.md'].mode, 'copy');
	},
	'the schema comes before the Go that queries it': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.ok(stageIndex(plan, 'backend/migrations/001_init.sql') < stageIndex(plan, 'backend/store/store.go'));
	},
	'no package is planned before one it imports': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.ok(stageIndex(plan, 'backend/models/node.go') < stageIndex(plan, 'backend/store/store.go'));
		assert.ok(stageIndex(plan, 'backend/store/store.go') < stageIndex(plan, 'backend/router.go'));
	},
	'a component is planned after the module it imports': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.ok(stageIndex(plan, 'web/src/lib/format.ts') < stageIndex(plan, 'web/src/ui/Badge.tsx'));
		assert.deepStrictEqual(plan.steps['web/src/ui/Badge.tsx'].deps, ['web/src/lib/format.ts']);
	},
	'ignored directories never become steps': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.strictEqual(plan.steps['node_modules/left-pad/index.js'], undefined);
	},
	'every source file lands in exactly one stage': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const listed = plan.stages.flatMap((s) => s.steps);
		assert.strictEqual(listed.length, new Set(listed).size, 'a file was planned twice');
		assert.strictEqual(listed.length, Object.keys(plan.steps).length);
		assert.ok(listed.includes('README.md'), 'supporting files are still part of the project');
	},
	'a Go step is checked by parsing that one file, not by building the package': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const checks = plan.steps['backend/store/store.go'].checks;
		assert.deepStrictEqual(checks.map((c) => c.kind), ['exists', 'shell']);
		assert.match(checks[1].cmd, /^gofmt -e -l "backend\/store\/store\.go"$/);
		assert.strictEqual(checks[1].emptyOutput, true);
	},
	'the stage that owns a package builds and tests it': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const stage = plan.stages.find((s) => s.id === 'backend/store');
		assert.deepStrictEqual(stage.checks.map((c) => c.cmd), ['go build ./store', 'go test ./store']);
		assert.strictEqual(stage.checks[0].cwd, 'backend');
	},
	'the module root package builds as .': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.strictEqual(plan.stages.find((s) => s.id === 'backend').checks[0].cmd, 'go build .');
	},
	'a stage that registers routes offers the API view': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const tools = plan.stages.find((s) => s.id === 'backend').tools.map((t) => t.command);
		assert.ok(tools.includes('burrow.flow.refresh'));
	},
	'a stage whose only router match is in a test file offers no API hint': () => {
		// A middleware test spins up a chi router to exercise the middleware. That
		// is not a stage that registers routes, and treating it as one fired the
		// hint four stages before there was anything to trace.
		const plan = buildPlan([
			file('backend/go.mod', 'module example.com/app\n\ngo 1.25.0\n'),
			file('backend/mw/mw.go', 'package mw\n\nfunc Auth() {}\n'),
			file('backend/mw/mw_test.go', 'package mw\n\nimport "github.com/go-chi/chi/v5"\n\nfunc TestAuth(t *testing.T) {\n\tr := chi.NewRouter()\n\tr.Route("/x", nil)\n}\n'),
		], { name: 'app', reference: '/ref' });
		const stage = plan.stages.find((s) => s.id === 'backend/mw');
		assert.ok(stage.steps.includes('backend/mw/mw_test.go'), 'the test file is still a step');
		assert.ok(!stage.tools.some((t) => t.command === 'burrow.flow.refresh'), 'but it does not register routes');
		assert.ok(stage.tools.some((t) => t.command === 'burrow.test.runAll'), 'the Test Lab hint is unaffected');
	},
	'a stage that mounts routes on a router it was handed offers no API hint': () => {
		// Six of merkle's eight registration sites look exactly like this: they
		// take a chi.Router and hang routes off it. flowscan seeds at NewRouter()
		// and can trace none of them until whatever calls it exists, so a stage
		// full of them is a stage where the API view still shows nothing.
		const plan = buildPlan([
			file('backend/go.mod', 'module example.com/app\n\ngo 1.25.0\n'),
			file('backend/admin/routes.go', 'package admin\n\nimport "github.com/go-chi/chi/v5"\n\nfunc RegisterRoutes(r chi.Router) {\n\tr.Route("/admin", func(r chi.Router) {\n\t\tr.Get("/usage", nil)\n\t})\n}\n'),
		], { name: 'app', reference: '/ref' });
		assert.ok(plan.stages.length, 'the package is still planned');
		assert.deepStrictEqual(
			plan.stages.filter((s) => s.tools.some((t) => t.command === 'burrow.flow.refresh')).map((s) => s.id),
			[], 'no stage offers the API view when nothing creates a router');
	},
	'the API hint waits for the file that creates the router': () => {
		const plan = buildPlan([
			...project(),
			// Registers routes on a router it is handed — earlier than backend/,
			// which is the package that actually calls chi.NewRouter().
			file('backend/admin/routes.go', 'package admin\n\nimport "github.com/go-chi/chi/v5"\n\nfunc RegisterRoutes(r chi.Router) {\n\tr.Route("/admin", nil)\n}\n'),
		], { name: 'app', reference: '/ref' });
		const hinted = plan.stages.filter((s) => s.tools.some((t) => t.command === 'burrow.flow.refresh')).map((s) => s.id);
		assert.ok(hinted.includes('backend'), 'the stage holding chi.NewRouter() offers it');
		assert.ok(!hinted.includes('backend/admin'), 'the stage that only mounts does not');
		assert.ok(stageIndex(plan, 'backend/admin/routes.go') < plan.stages.findIndex((s) => s.id === 'backend'),
			'and it really did come first, so this is a gate and not an ordering accident');
	},

	'a stage with a test file offers the Test Lab': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const tools = plan.stages.find((s) => s.id === 'backend/store').tools.map((t) => t.command);
		assert.ok(tools.includes('burrow.test.runAll'));
	},
	'foundations carry the one-off dependency installs': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.deepStrictEqual(plan.stages[0].setup, ['cd backend && go mod download', 'cd web && npm install']);
	},
	'a package doc comment becomes the stage blurb': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.match(plan.stages.find((s) => s.id === 'backend/models').blurb, /^Package models holds the shapes/);
	},
	'dependents run the graph backwards': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.deepStrictEqual(dependents(plan, 'web/src/lib/format.ts'), ['web/src/ui/Badge.tsx']);
		assert.ok(dependents(plan, 'backend/models/node.go').includes('backend/store/store.go'));
	},
	'the counts describe the whole project': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		assert.strictEqual(plan.counts.steps, Object.keys(plan.steps).length);
		assert.strictEqual(plan.counts.stages, plan.stages.length);
		assert.ok(plan.counts.lines > 0);
	},
	'planning is deterministic': () => {
		const a = JSON.stringify(buildPlan(project(), { name: 'app', reference: '/ref' }));
		const b = JSON.stringify(buildPlan(project().reverse(), { name: 'app', reference: '/ref' }));
		assert.strictEqual(a, b);
	},
	// --- route annotations ----------------------------------------------------
	'routes reach the registration site, the handler and the middleware': () => {
		const index = routeIndex(flows(60), 'backend');
		assert.deepStrictEqual(index.get('backend/router.go'), ['GET /api/nodes', 'POST /api/nodes']);
		assert.deepStrictEqual(index.get('backend/store/store.go'), ['GET /api/nodes']);
		assert.deepStrictEqual(index.get('backend/middleware/auth.go'), ['POST /api/nodes']);
	},
	'a degraded scan annotates nothing at all, not a little': () => {
		// The stale-binary case: flowscan still succeeds and still emits flows,
		// it just traces six of them. Six explained routes read as though the
		// other two hundred serve nothing.
		assert.strictEqual(routeIndex(flows(6), 'backend'), undefined);
		assert.strictEqual(routeIndex(undefined, 'backend'), undefined);
		assert.strictEqual(routeIndex({ coverage: { traced: 200 }, flows: [] }, 'backend'), undefined);
	},
	'annotations name three routes and count the rest': () => {
		const many = { coverage: { traced: 99 }, flows: [] };
		for (let i = 0; i < 7; i++) {
			many.flows.push({ method: 'GET', path: `/api/r${i}`, file: 'router.go', nodes: [{ file: 'store/store.go' }] });
		}
		const plan = buildPlan(project(), { name: 'app', reference: '/ref', routes: routeIndex(many, 'backend') });
		const step = plan.steps['backend/store/store.go'];
		assert.strictEqual(step.routes.length, 3);
		assert.strictEqual(step.routeCount, 7);
	},
	'annotation changes no ordering and no check': () => {
		const bare = buildPlan(project(), { name: 'app', reference: '/ref' });
		const rich = buildPlan(project(), { name: 'app', reference: '/ref', routes: routeIndex(flows(60), 'backend') });
		assert.deepStrictEqual(rich.stages.flatMap((s) => s.steps), bare.stages.flatMap((s) => s.steps));
		for (const id of Object.keys(bare.steps)) {
			assert.deepStrictEqual(rich.steps[id].checks, bare.steps[id].checks);
		}
		assert.strictEqual(bare.steps['backend/router.go'].routes, undefined);
		assert.deepStrictEqual(rich.steps['backend/router.go'].routes, ['GET /api/nodes', 'POST /api/nodes']);
	},

	// --- the invariant --------------------------------------------------------
	// This is the assertion the whole feature rests on, and it is checked against
	// the EMITTED plan, not against topoSort: an ordering policy can be wrong in
	// ways the sort cannot see.
	'the emitted plan is a valid topological order': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		const real = orderViolations(plan).filter((v) => !v.cyclic);
		assert.deepStrictEqual(real, [], real.map((v) => `${v.step} @${v.at} needs ${v.dep} @${v.depAt}`).join('\n'));
	},
	'the invariant catches a step moved ahead of what it imports': () => {
		const plan = buildPlan(project(), { name: 'app', reference: '/ref' });
		// Swap the two web stages so Badge.tsx precedes the module it imports.
		const stages = plan.stages.slice();
		const lib = stages.findIndex((s) => s.id === 'web/src/lib');
		const ui = stages.findIndex((s) => s.id === 'web/src/ui');
		[stages[lib], stages[ui]] = [stages[ui], stages[lib]];
		const broken = orderViolations({ ...plan, stages }).filter((v) => !v.cyclic);
		assert.ok(broken.length, 'a deliberately mis-ordered plan must be reported');
		assert.ok(broken.some((v) => v.step === 'web/src/ui/Badge.tsx' && v.dep === 'web/src/lib/format.ts'));
	},
	'a genuine import cycle is reported as cyclic, not as a defect': () => {
		const cyclic = [
			file('web/package.json', '{"name":"web"}'),
			file('web/src/a/one.ts', "import { two } from '../b/two';\nexport const one = two;\n"),
			file('web/src/b/two.ts', "import { one } from '../a/one';\nexport const two = one;\n"),
		];
		const plan = buildPlan(cyclic, { name: 'web', reference: '/ref' });
		const all = orderViolations(plan);
		assert.ok(all.length, 'the cycle does produce an out-of-order pair');
		assert.deepStrictEqual(all.filter((v) => !v.cyclic), [], 'but none of it is a defect');
	},

	'an empty project plans nothing rather than crashing': () => {
		const plan = buildPlan([], { name: 'nothing', reference: '/ref' });
		assert.deepStrictEqual([plan.stages.length, plan.counts.steps], [0, 0]);
	},
};

let failed = 0;
for (const [name, run] of Object.entries(cases)) {
	try {
		run();
		console.log(`  ✓ ${name}`);
	} catch (error) {
		failed++;
		console.error(`  ✗ ${name}\n    ${error.message}`);
	}
}
console.log(`${Object.keys(cases).length - failed}/${Object.keys(cases).length} passed`);
process.exit(failed ? 1 : 0);
